# Backend/utils/hv_feature_reference.py
TRAINED_FEATURES = [
    'hydrogen_percentage',
    'fuel_cell_age_years',
    'fuel_cell_efficiency',
    'ambient_temp',
    'terrain_slope',
    'speed_avg_kmph',
    'acceleration_level',
    'hvac_on',
    'driving_mode_normal',
    'driving_mode_sport',
    'driving_mode_eco',
    'drive_type_FWD',
    'drive_type_RWD',
    'drive_type_AWD',
    'cargo_volume_liters',
    'top_speed_kmph',
    'total_power_kw',
    'total_torque_nm',
    'speed_sq',
    'abs_slope',
    'hydrogen_per_year',
    'age_squared',
    'h2_x_efficiency',
    'h2_x_age',
]